name: Coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate coverage report
        run: npm run coverage

#      - name: Convert coverage.out to coverage.lcov
#        uses: jandelgado/gcov2lcov-action@v1

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/lcov.info

      - name: Verify coverage percentage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: './coverage/lcov.info'
          min_coverage: 50
