name: Dependency Check

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch that the workflow should run with'
        default: 'main'
        required: false
        type: string

jobs:
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run dependency check
        run: npm run check
