name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test
#    strategy:
#      matrix:
#        go-version: [ 1.19 ]
#        platform: [ windows-latest, macos-latest, ubuntu-latest ]
#    runs-on: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run unit test
        run: npm run test:unit

      - name: Run integrated test
        run: npm run test:integrated
